import sqlite3
con = sqlite3.connect("tutorial.db")
cur = con.cursor()
a=input()
cur.execute("Insert into line values(?)",[a])
con.commit()
otvet=cur.execute('select * from line')
print(otvet.fetchall())
con.commit()
cur.execute("delete  from line where tg_kanal='ewqewqeqe'")
otvet=cur.execute('select * from line')
print(otvet.fetchall())
con.commit()
